dist: trusty
sudo: false
group: beta
language: c
os:
  - osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nim ; fi

script:
  - nim c testrunner.nim
  - ./testrunner -d tests/test_glob.nim -- -p:.

branches:
  except:
    - gh-pages
